apiVersion: v1
kind: Service
metadata:
  name: iris-service
  namespace: iris-production
spec:
  type: NodePort
  selector:
    app: iris-app
  ports:
    - protocol: TCP
      port: 80         # Port accessible inside the cluster
      targetPort: 8000 # Port your FastAPI is listening on
      nodePort: 30001  # Port accessible via http://localhost:30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-deployment
  namespace: iris-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-app
  template:
    metadata:
      labels:
        app: iris-app
    spec:
      containers:
      - name: iris-container
        image: krithik9/iris-service:v2
        ports:
        - containerPort: 8000
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/root/.config/gcloud/application_default_credentials.json"
        volumeMounts:
        - name: gcp-adc-token
          mountPath: /root/.config/gcloud
          readOnly: true
      volumes:
      - name: gcp-adc-token
        hostPath:
          path: "/run/desktop/mnt/host/c/Users/hp/AppData/Roaming/gcloud"
          type: DirectoryOrCreate